# Generated by Django 4.2.8 on 2023-12-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.CharField(max_length=30)),
                ('des', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
